import {
  generateTaskId,
  PREDEFINED_USERS,
  TASK_CATEGORIES,
  TASK_STATUS,
  tasks,
} from "./taskData.js";

const validStatuses = Object.values(TASK_STATUS);

// Converts a list of allowed values into readable text for error messages.
const formatAllowedValues = (values) => values.join(", ");

// Ensures that only the three predefined users can perform task operations.
const validateUser = (assignedUser) => {
  if (!PREDEFINED_USERS.includes(assignedUser)) {
    throw new Error(
      `Invalid user "${assignedUser}". Valid users are: ${formatAllowedValues(
        PREDEFINED_USERS
      )}.`
    );
  }
};

// Ensures that task status updates use one of the allowed status values.
const validateStatus = (status) => {
  if (!validStatuses.includes(status)) {
    throw new Error(
      `Invalid status "${status}". Valid statuses are: ${formatAllowedValues(
        validStatuses
      )}.`
    );
  }
};

// Ensures task categories match one of the predefined category values.
const validateCategory = (category) => {
  if (!TASK_CATEGORIES.includes(category)) {
    throw new Error(
      `Invalid category "${category}". Valid categories are: ${formatAllowedValues(
        TASK_CATEGORIES
      )}.`
    );
  }
};

// Validates and trims required text fields such as task names.
const validateRequiredText = (value, fieldName) => {
  if (typeof value !== "string" || value.trim() === "") {
    throw new Error(`${fieldName} is required and must be a non-empty string.`);
  }

  return value.trim();
};

// Ensures the task ID has the same format as IDs generated by this application.
const validateTaskId = (taskId) => {
  if (!Number.isInteger(taskId) || taskId < 1) {
    throw new Error(
      `Invalid task ID "${taskId}". Task IDs must be positive integers.`
    );
  }
};

// Creates a defensive copy so callers cannot directly mutate stored tasks.
const copyTask = (task) => ({ ...task });

// Finds a task and its array index by ID across all users.
// Authorization is checked separately so missing tasks and unauthorized
// operations can produce different, meaningful errors.
const findTaskRecordById = (taskId) => {
  validateTaskId(taskId);

  const taskIndex = tasks.findIndex((currentTask) => currentTask.id === taskId);

  if (taskIndex === -1) {
    throw new Error(`Invalid task ID "${taskId}". No task exists with that ID.`);
  }

  return {
    task: tasks[taskIndex],
    taskIndex,
  };
};

// Confirms that the requesting user owns the task before changing or deleting it.
const validateTaskOwnership = (task, assignedUser, action) => {
  if (task.assignedUser !== assignedUser) {
    throw new Error(
      `Unauthorized ${action}: task ${task.id} belongs to ${task.assignedUser}, not ${assignedUser}.`
    );
  }
};

// Adds a new task for one of the predefined users.
export const addTask = (taskName, category, assignedUser) => {
  validateUser(assignedUser);

  const trimmedTaskName = validateRequiredText(taskName, "Task name");
  const trimmedCategory = validateRequiredText(category, "Task category");
  validateCategory(trimmedCategory);

  const newTask = {
    // Primary key: uniquely identifies this task in memory.
    id: generateTaskId(),
    taskName: trimmedTaskName,
    category: trimmedCategory,
    status: TASK_STATUS.PENDING,
    assignedUser,
  };

  tasks.push(newTask);

  return copyTask(newTask);
};

// Returns only the tasks assigned to the requested predefined user.
export const viewTasksByUser = (assignedUser) => {
  validateUser(assignedUser);

  return tasks
    .filter((task) => task.assignedUser === assignedUser)
    .map(copyTask);
};

// Updates the status of a task only when the requesting user owns that task.
export const updateTaskStatus = (taskId, assignedUser, status) => {
  validateUser(assignedUser);
  validateStatus(status);

  const { task } = findTaskRecordById(taskId);
  validateTaskOwnership(task, assignedUser, "update");

  task.status = status;

  return copyTask(task);
};

// Deletes a task only when the requesting user owns that task.
export const deleteTask = (taskId, assignedUser) => {
  validateUser(assignedUser);

  const { task, taskIndex } = findTaskRecordById(taskId);
  validateTaskOwnership(task, assignedUser, "deletion");

  const [deletedTask] = tasks.splice(taskIndex, 1);

  return copyTask(deletedTask);
};
